### ISSUE TITLE
Include example YAML config file

### ISSUE THREAD

**Issue by Qrbaker** [TrueBrain/TrueWiki#101]
It would be really helpful for others if there was a YAML .default or similar for configuring the wiki. In order to get the schema I was able to use the file in the OpenTTD wikidata repo, but it required a lot of hunting to first discover a `.truewiki.yml` file was even required.

https://github.com/OpenTTD/wiki-data/blob/master/.truewiki.yml

Thanks for making this!

**Comment by TrueBrain** [comment]
Oops .. you are absolutely right, there should be an example configuration file in this repository too. Sorry about that! There is no need that anyone should hunt for that, honestly :) I will see if I can fix that this week! Tnx for letting me know :)

OpenTTD doesn't use all options; all possibly options are currently only described in code here:
https://github.com/TrueBrain/TrueWiki/blob/master/truewiki/config.py

I will integrate this with the example config, also explaining a bit what each setting does. That should help others a bit more :)

If there are any other issues or problems, please do reach out! Tnx :)

**Comment by Qrbaker** [comment]
You bet! We're looking at using this wiki software for the Crafty Minecraft Server Controller project (https://craftycontrol.com/) and will definitely upstream and/or share our notes as they come up
