### ISSUE TITLE
ARM Docker Images

### ISSUE THREAD

**Issue by Qrbaker** [TrueBrain/TrueWiki#254]
Hey its been a second. We're migrating to a cheaper (oracle) server that is running ARMv8. Do you mind if we build our own image for ARM?

**Comment by Qrbaker** [comment]
Okay, looks like this *does* run on ARM hardware, it just has a warning because it isn't listed as a target.

**Comment by TrueBrain** [comment]
It is a pure Python application, so it should run for sure :D

I can see if I can also publish other formats for sure; should make it easier for other people too :)

**Comment by Qrbaker** [comment]
Yeah, targeting multiarch would be nice (w/ AMD64, ARM64 in the manifest)

**Comment by Qrbaker** [comment]
We've got it building on our end. I can send you the dockerfile if it would help.

**Comment by TrueBrain** [comment]
It finally happened! It only took rewritten the complete GitHub Workflow :P But the latest release (v1.7.0) has [both AMD64 as ARM64 images on GitHub Container Registry](https://github.com/TrueBrain/TrueWiki/pkgs/container/truewiki).

Additionally, versions gained a `v` :) About time ;)
