### ISSUE TITLE
Change/Merge Conflict Handling

### ISSUE THREAD

**Issue by Qrbaker** [TrueBrain/TrueWiki#256]
In mediawiki servers, a user editing a page will get notified if the page has changed while they made edits, and will ask if they want to overwrite or restart their edit.

Currently, from my testing, Truewiki just works on last-write-wins. This isn't a terribly-big deal as we still have the commit history and can do merges, but it might be worth updating the code to grab the commit hash when a user starts editing, and giving them a warning message if upstream's HEAD points to a new hash when they submit changes.

**Comment by TrueBrain** [comment]
Absolutely; also should be relative easy, by simply sending the last-modified date of the file to the client, which he returns on saving of the edited page. If they no longer match, warn the user about a possible change. Nice idea!

**Comment by Qrbaker** [comment]
Glad you think so. I'll try implementing both solutions, and see which turns out nicer.

**Comment by TrueBrain** [comment]
Do know that git is just one of the backends; it is also perfectly fine to run TrueWiki with a "local" storage :) So you cannot assume you have a commit hash available :)

**Comment by Qrbaker** [comment]
> Do know that git is just one of the backends; it is also perfectly fine to run TrueWiki with a "local" storage :) So you cannot assume you have a commit hash available :)

Ah, good point. I think I'll just implement last-modified checking first. If for some reason that isn't enough, we can come back to using git hashes.

**Comment by Qrbaker** [comment]
@TrueBrain in regards to sending the timestamp to the client, would you think it would be better to save as a cookie (as a unix timestamp), or actually save as a page element (i.e. put a string at the bottom of the page that says "last changed on YYYY-MM-DD at HH:MM:SS)?

I could see it working either way.

**Comment by TrueBrain** [comment]
Implemented with #258.
