### ISSUE TITLE
Screen sizing for large monitors and small phones

### ISSUE THREAD

**Issue by MingweiSamuel** [TrueBrain/TrueWiki#89]
User pointed out that a lot of screen space is wasted on big monitors, and also that the pages don't scale for mobile.

I'd be willing to put a bit of work into the CSS if people agree. Also not sure if changes are needed in this repo or in https://github.com/OpenTTD/wiki-data

https://github.com/TrueBrain/TrueWiki/blob/04b2907c3ff9bb9346a079a23dd1b0cf7aa15828/static/css/truewiki.css#L2-L4

**Comment by TrueBrain** [comment]
PRs for CSS can be made to this repository for now; it will be split up, but for now that is fine. https://github.com/TrueBrain/TrueWiki/tree/master/static/css contains all the CSS.

Regarding your finding:

`lot of screen space is wasted on big monitors`
This is a matter of opinion. Many websites have been switching to fixed width, and for a good reason. Even Github does, as example. Using the full width on a 2k or 4k monitor is very annoying in reading, especially with a site that has a lot of text that has to be read (as in, a wiki). Limiting the width makes it more natural to read, and easier on the eye. So the width of `1020px` is a deliberate action, and not one by accident. We are always willing to talk stuff over, so if you disagree, bring your argument, but it might be good to know that all `*.openttd.org` run similar CSS, all limiting the width of the website. In general, people with big monitors don't have websites fullscreen anymore ;)

Regarding mobile, in the testing we did it scales "good enough" on mobile, but the CSS in no way is created to render properly on mobile. PRs to improve that are very welcome. Ideally we also would like to backport those to https://www.openttd.org, https://bananas.openttd.org, https://servers.openttd.org, all running the same base CSS.

In general you will find we know very little about HTML and CSS, but we have a preference how things look. For example: most of us agree that the "external link" icon you see next to external links is far from ideal .. but it is the best we could do :D And there are many more places where the CSS could really really use improvements :) So feel welcome, and PR away :D

**Comment by TrueBrain** [comment]
We just moved all the CSS and images to the data-repositories. Please create PRs against:

https://github.com/OpenTTD/wiki-data-staging

So it can be reviewed and deployed to staging. We will then sync that to https://github.com/OpenTTD/wiki-data for it to go to production.

Going to close this issue here now if you don't mind. Feel free to open up an issue in either of the other two repositories if you want to talk over some points.

Again, would love to see CSS contributions, they are very welcome :D Tnx!

**Comment by MingweiSamuel** [comment]
Thanks! I'll find some time and make a PR hopefully soon
